server:
  port: 8080

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_database
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db.changelog/db.changelog-master.yaml

number:
  generate:
    service:
      url: "http://localhost:8081/api/v1"
      numbers-uri: "/numbers"